export const SETTINGS_KEYS = {
  PLATFORM_FEE_PERCENT: 'PLATFORM_FEE_PERCENT',
  POINTS_TO_MYR_RATE: 'POINTS_TO_MYR_RATE',
  MIN_WITHDRAWAL_MYR: 'MIN_WITHDRAWAL_MYR'
} as const;

export const DEFAULT_SETTINGS: Record<string, string> = {
  [SETTINGS_KEYS.PLATFORM_FEE_PERCENT]: '10',
  [SETTINGS_KEYS.POINTS_TO_MYR_RATE]: '0.01',
  [SETTINGS_KEYS.MIN_WITHDRAWAL_MYR]: '50'
};
